### ISSUE TITLE
How to have different css styles for different filters

### ISSUE THREAD

**Issue by leocrawf** [moayadnajd/nativescript-filter-select#38]
Thank you for this excellent plugin. All works well except for one issue. My filters do not all have the same background color so the selected color could be black in once css declaration and white in the other. The specific property I am looking to change is this:

    .filter-select-label.selected{
      color:black;
    }

How could I change this property for different filters?

**Comment by moayadnajd** [comment]
make example on https://play.nativescript.org/

**Comment by leocrawf** [comment]
This is easily fixed using page level css.

**Comment by dudipsh** [comment]
@leocrawf how?
i try 

```css
.layout {
  FilterSelect {
    color: #ffffff;
    .filter-select-label {
      color: #ffffff;
    }
  }
  .filter-select-label, .hint {
    color: #ffffff;
  }
}
```

```xml
<Page class="layout">
   <FilterSelect
                                class="text-place text-center p-0 m-0 no-btn"
                                row="3" col="1"
                                xbtn="x"
                                render="label"
                                height="100"
                                hint="{{selectedPlace.name}}"
                                multiple="false"
                                [items]="user.userDetails.places"
                                (change)="onitemselected($event)"
                                modal_title="item"
                                search_param="name"
                                primary_key="name">
                        </FilterSelect>
</Page>
```

the color didn't changed
