### ISSUE TITLE
Change filter dialog background color

### ISSUE THREAD

**Issue by weijyewang** [moayadnajd/nativescript-filter-select#52]
Hi, thanks for the nice library. In my app.css I style my `Page `to have `color: #fff `and `background: black`:

 ```CSS
TextView,
TextField {
  padding: 10;
  font-size: 16;
  color: #fff;
  /* border-bottom-width: 1; */
  /* border-bottom-color:#fff;  */
  border-width: 0 0 1 0; 
  border-color: #fff;
  placeholder-color: #a3a3a3;
}
```
This resulting in the font become white color but the background is also white as well when the filter dialog came up
![image](https://user-images.githubusercontent.com/8890603/46945969-dca9d180-d0a8-11e8-81df-d671c726fe4a.png)

How do I change the modal background to be black?
