### ISSUE TITLE
Can't change hint text

### ISSUE THREAD

**Issue by dudipsh** [moayadnajd/nativescript-filter-select#60]
Hi, 
How to change the "hint" color?
is always white!

I've try everything
```css
.hint {
  color: #00ff23;
}
FilterSelect {
  background-color: #303030;
  color: #00ff23;
  Lable {
    color: #00ff23;

  }
}

.filter-select-label {
  color: #00ff23;
}
```
